---
- name: Fetch messages  
  hosts: localhost
  vars:
    rabbitmq_api_url: "http://{{ 172.26.0.6 }}:{{ 5672 }}/api/queues/{{ awx }}/{{ awxQueue }}/get"

  tasks:
    - name: Get message from RabbitMQ
      uri:
        url: "amqp://awxuser:awxpass@172.26.0.2:15672/%2F"
        method: GET
        status_code: 200
        body_format: raw
      register: rabbitmq_response

    - name: Print message from RabbitMQ
      debug:
        msg: "{{ rabbitmq_response.json }}"
