- name: Fetch RabbitMQ queue data
  hosts: localhost
  vars:
    rabbitmq_username: admin
    rabbitmq_password: admin
  tasks:
    - name: Fetch RabbitMQ queues
      uri:
        url: "https://rbmq-market-place.apps.openshift.sys.onetech-group.corp/api/queues"
        method: GET
        user: "{{ rabbitmq_username }}"
        password: "{{ rabbitmq_password }}"
        validate_certs: false
        force_basic_auth: yes
        return_content: yes
      register: rabbitmq_queues
    - debug:
        var: rabbitmq_queues.content