- name: Retrieve messages from RabbitMQ queue
  hosts: localhost
  gather_facts: no
  vars:
    rabbitmq_host: "localhost"
    rabbitmq_port: "5672"
    rabbitmq_user: "awxUser"
    rabbitmq_pass: "awxuser"
    queue_name: "awxQueue"
  tasks:
    - name: Retrieve messages from RabbitMQ queue
      rabbitmq_queue:
        name: "Retrieve messages"
        login_user: "{{ rabbitmq_user }}"
        login_password: "{{ rabbitmq_pass }}"
        login_host: "{{ rabbitmq_host }}"
        login_port: "{{ rabbitmq_port }}"
    - name: Get messages from queue
      shell: |
        rabbitmqadmin get queue=awxQueue count=1
      register: result
    - name: Display messages
      debug:
        var: result.messages

