---
- name: Get message from RabbitMQ queue
  hosts: Rb
  become: yes
  collections:
    - rabbitmq.rabbitmq
  tasks:
    - name: Get message
      rabbitmq_queue:
        login_host: 172.26.0.2
        login_user: admin
        login_password: password
        name: awxQueue
        vhost: /
        state: present
      register: result
    - name: Display message
      debug:
        var: result
