---
- name: Get message from RabbitMQ queue
  hosts: VmCloud
  become: yes

  tasks:

    - name: Install RabbitMQ Python package
      pip:
        name: pika

    - name: Consume using Lookup plugin
      set_fact:
        contents: "{{ lookup('rabbitmq', url='amqp://hazem:password@10.112.60.53:5672/awxHost', queue='awxQueue') }}"

    - name: debug
      debug:
        msg: "the queue contained {{ contents }}"
