---
- name: Consume message from queue
  hosts: RabbitMQGrp
  become: false
  vars:
    queue_name: awxQueue
  tasks:
    - name: Consume from RabbitMQ
      pip:
        name: pika
      register: pika_result
    - name: Consume message
      set_fact:
        message: "{{ pika_result | json_query('results[0].item.stdout_lines[0]') }}"
    - name: Debug message
      debug:
        var: message


